import type { CSSProperties } from "react";

/** Co-located styles for StatsTab. */
export const s = {
  wrap: { display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  tiles: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(170px, 1fr))",
    gap: 14,
  } satisfies CSSProperties,
  tile: {
    padding: "14px 16px",
    borderRadius: 9,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    display: "flex",
    alignItems: "center",
    gap: 12,
  } satisfies CSSProperties,
  tileText: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  tileLabel: {
    fontSize: 10.5,
    fontWeight: 600,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  tileValue: {
    fontSize: 26,
    fontWeight: 700,
    letterSpacing: "-0.02em",
    marginTop: 6,
    display: "flex",
    alignItems: "baseline",
    gap: 4,
  } satisfies CSSProperties,
  tileUnit: { fontSize: 13, fontWeight: 500, color: "var(--text-secondary)" } satisfies CSSProperties,
  panels: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap: 14,
    alignItems: "start",
  } satisfies CSSProperties,
  panel: {
    padding: 16,
    borderRadius: 9,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  panelHead: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 10.5,
    fontWeight: 600,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 12,
  } satisfies CSSProperties,
  agentRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "9px 11px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    marginBottom: 6,
    fontSize: 13,
  } satisfies CSSProperties,
  agentName: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  empty: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  // The honest denominator: how many findings from runs that used this skill
  // could not be attributed to any skill at all.
  caveat: {
    fontSize: 11.5,
    lineHeight: 1.55,
    color: "var(--text-secondary)",
    padding: "10px 12px",
    borderRadius: 7,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
  } satisfies CSSProperties,
  donutWrap: { display: "flex", alignItems: "center", gap: 20 } satisfies CSSProperties,
  donutSvg: { transform: "rotate(-90deg)", flexShrink: 0 } satisfies CSSProperties,
  legend: { display: "flex", flexDirection: "column", gap: 8, minWidth: 0 } satisfies CSSProperties,
  legendRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 13,
  } satisfies CSSProperties,
  legendSwatch: (color: string): CSSProperties => ({
    width: 9,
    height: 9,
    borderRadius: 2,
    background: color,
    flexShrink: 0,
  }),
  legendLabel: { color: "var(--text-secondary)", flex: 1 } satisfies CSSProperties,
  legendValue: { color: "var(--text-primary)", fontWeight: 600 } satisfies CSSProperties,
} as const;
