import type { CSSProperties } from "react";

/** Co-located styles for AgentLane. */
export const s = {
  lane: (accent: string): CSSProperties => ({
    borderStyle: "solid",
    borderTopWidth: 3,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderTopColor: accent,
    borderRightColor: "var(--border)",
    borderBottomColor: "var(--border)",
    borderLeftColor: "var(--border)",
    borderRadius: 10,
    background: "var(--bg-surface)",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
  }),
  header: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 14px",
    borderBottom: "1px solid var(--border)",
    flexWrap: "wrap",
  } satisfies CSSProperties,
  agentName: { fontWeight: 600, fontSize: 14, color: "var(--text-primary)" } satisfies CSSProperties,
  meta: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  spacer: { flex: 1 } satisfies CSSProperties,
  body: { padding: 14, display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  summary: { fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.5 } satisfies CSSProperties,
  emptyNote: { fontSize: 13, color: "var(--text-muted)", padding: "6px 0" } satisfies CSSProperties,
  errorNote: {
    fontSize: 13,
    color: "var(--crit)",
    background: "var(--crit-bg)",
    borderRadius: 6,
    padding: "10px 12px",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  findingsList: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  capsNote: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  scoreRing: {
    position: "relative",
    width: 28,
    height: 28,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  } satisfies CSSProperties,
  scoreRingNum: {
    position: "absolute",
    fontSize: 10.5,
    fontWeight: 700,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  /** Visually hidden but present in the accessibility tree — the live region
   *  that announces a lane's status change (AC-47). Content mirrors what the
   *  status badge already shows sighted users. */
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clip: "rect(0, 0, 0, 0)",
    whiteSpace: "nowrap",
    border: 0,
  } satisfies CSSProperties,
} as const;
