import type { CSSProperties } from "react";

/** Co-located styles for the Export to CI wizard. */
export const s = {
  outer: {
    display: "flex",
    flexDirection: "column",
    gap: 20,
    minWidth: 0,
  } satisfies CSSProperties,
  stepRail: { padding: "4px 0" } satisfies CSSProperties,
  body: { display: "flex", flexDirection: "column", gap: 16, minHeight: 220 } satisfies CSSProperties,
  hint: { fontSize: 12, color: "var(--text-muted)", lineHeight: 1.5 } satisfies CSSProperties,
  targetRow: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  sectionLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.04em",
    color: "var(--text-muted)",
    textTransform: "uppercase",
  } satisfies CSSProperties,
  previewLayout: {
    display: "grid",
    gridTemplateColumns: "minmax(180px, 260px) 1fr",
    gap: 16,
    alignItems: "start",
    minWidth: 0,
  } satisfies CSSProperties,
  fileList: { display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  fileRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    padding: "6px 8px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  filePath: { fontSize: 12, minWidth: 0, overflowWrap: "anywhere" } satisfies CSSProperties,
  workflowPane: { display: "flex", flexDirection: "column", gap: 8, minWidth: 0 } satisfies CSSProperties,
  workflowCode: {
    margin: 0,
    padding: 12,
    borderRadius: 7,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
    fontSize: 12,
    lineHeight: 1.5,
    maxHeight: 360,
    overflow: "auto",
    whiteSpace: "pre",
  } satisfies CSSProperties,
  busy: { display: "flex", alignItems: "center", gap: 10, padding: "24px 0" } satisfies CSSProperties,
  fieldGroup: { display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  triggerRow: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  secretsBox: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: 12,
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  branchProtectionBox: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    padding: 12,
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  errorBox: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: 14,
    borderRadius: 8,
    border: "1px solid var(--crit)",
    background: "var(--crit-bg)",
  } satisfies CSSProperties,
  errorText: { fontSize: 13, color: "var(--crit)" } satisfies CSSProperties,
  confirmBox: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 10,
    padding: "32px 16px",
    textAlign: "center",
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    paddingTop: 12,
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
};
