import type { CSSProperties } from "react";

/** Co-located styles for the skill editor's ContextTab. */
export const s = {
  // Grid, not the flex `wrap` below: the preview panel is a sibling column that
  // only exists once a document is selected, so `wrap` keeps its own single-
  // column width and the grid just decides whether there is a second one.
  outer: (previewOpen: boolean): CSSProperties => ({
    display: "grid",
    gridTemplateColumns: previewOpen ? "minmax(420px, 760px) minmax(320px, 420px)" : "minmax(0, 760px)",
    gap: 16,
    alignItems: "start",
  }),
  wrap: { display: "flex", flexDirection: "column", gap: 10, minWidth: 0 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap" } satisfies CSSProperties,
  h2: { fontSize: 15, fontWeight: 650 } satisfies CSSProperties,
  search: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 10px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    width: 200,
  } satisfies CSSProperties,
  searchInput: {
    flex: 1,
    fontSize: 12,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  hint: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  warning: { fontSize: 12, color: "var(--warn)" } satisfies CSSProperties,
  error: { fontSize: 12, color: "var(--crit)" } satisfies CSSProperties,
  sectionLabel: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginTop: 8,
  } satisfies CSSProperties,
  row: (opts: { attached: boolean; dragging: boolean; dimmed: boolean }): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 10px",
    borderRadius: 7,
    marginBottom: 4,
    border: `1px solid ${opts.dragging ? "var(--accent)" : "var(--border)"}`,
    background: opts.attached ? "var(--bg-surface)" : "transparent",
    opacity: opts.dimmed ? 0.55 : 1,
    cursor: opts.attached ? "grab" : "default",
  }),
  handle: {
    color: "var(--text-muted)",
    display: "inline-flex",
    flexShrink: 0,
  } satisfies CSSProperties,
  handleSpacer: { width: 14, flexShrink: 0 } satisfies CSSProperties,
  path: { flex: 1, fontSize: 12.5, fontWeight: 500, wordBreak: "break-all" } satisfies CSSProperties,
  moveBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 22,
    height: 22,
    borderRadius: 5,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    color: "var(--text-secondary)",
    cursor: "pointer",
    flexShrink: 0,
  } satisfies CSSProperties,
  order: {
    fontSize: 11,
    color: "var(--text-muted)",
    minWidth: 18,
    textAlign: "right",
    flexShrink: 0,
  } satisfies CSSProperties,
  serialization: {
    marginTop: 12,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  serializationTitle: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  serializationCode: {
    fontSize: 12,
    color: "var(--text-primary)",
    background: "var(--code-bg)",
    borderRadius: 6,
    padding: "6px 9px",
  } satisfies CSSProperties,
} as const;
