import type { CSSProperties } from "react";

export const s = {
  card: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
  } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 10,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  headerLeft: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  whyBlock: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  why: {
    fontSize: 14,
    color: "var(--text-primary)",
    lineHeight: 1.55,
    whiteSpace: "pre-wrap",
  } satisfies CSSProperties,
  note: {
    marginTop: 10,
    fontSize: 12.5,
    color: "var(--text-tertiary)",
  } satisfies CSSProperties,
  sectionTitle: {
    fontSize: 11.5,
    textTransform: "uppercase",
    letterSpacing: 0.4,
    color: "var(--text-tertiary)",
    marginTop: 16,
    marginBottom: 8,
  } satisfies CSSProperties,
  risks: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
  risk: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    padding: "10px 12px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-hover)",
  } satisfies CSSProperties,
  riskHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  riskTitle: {
    fontSize: 13.5,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  riskExplanation: {
    fontSize: 13,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  focusList: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
  } satisfies CSSProperties,
  focusRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 0",
    background: "none",
    border: "none",
    textAlign: "left",
    cursor: "pointer",
    width: "100%",
  } satisfies CSSProperties,
  focusPath: {
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12.5,
    color: "var(--accent)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    maxWidth: 320,
  } satisfies CSSProperties,
  focusReason: {
    fontSize: 12.5,
    color: "var(--text-tertiary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  meta: {
    marginTop: 14,
    paddingTop: 12,
    borderTop: "1px solid var(--border)",
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    alignItems: "center",
    fontSize: 12,
    color: "var(--text-tertiary)",
  } satisfies CSSProperties,
} as const;
