import type { CSSProperties } from "react";
import { EVAL_METRIC_COLORS } from "@/components/eval-metric-bar";

export const s = {
  wrap: { display: "flex", flexDirection: "column", gap: 24, padding: "20px 24px" } satisfies CSSProperties,
  section: { display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  sectionHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  } satisfies CSSProperties,
  sectionTitle: { fontSize: 15, fontWeight: 700 } satisfies CSSProperties,
  sectionSubtitle: { fontSize: 12.5, color: "var(--text-secondary)" } satisfies CSSProperties,
  metricRow: { display: "flex", gap: 12, flexWrap: "wrap" } satisfies CSSProperties,
  metricCard: {
    flex: "1 1 140px",
    padding: "12px 14px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  metricLabel: {
    fontSize: 11,
    letterSpacing: "0.05em",
    color: "var(--text-muted)",
    textTransform: "uppercase",
  } satisfies CSSProperties,
  metricValue: { fontSize: 22, fontWeight: 700, marginTop: 4 } satisfies CSSProperties,
  metricValueRecall: {
    fontSize: 22,
    fontWeight: 700,
    marginTop: 4,
    color: EVAL_METRIC_COLORS.recall,
  } satisfies CSSProperties,
  metricValuePrecision: {
    fontSize: 22,
    fontWeight: 700,
    marginTop: 4,
    color: EVAL_METRIC_COLORS.precision,
  } satisfies CSSProperties,
  metricValueCitation: {
    fontSize: 22,
    fontWeight: 700,
    marginTop: 4,
    color: EVAL_METRIC_COLORS.citation,
  } satisfies CSSProperties,
  metricDelta: { fontSize: 12, marginTop: 4 } satisfies CSSProperties,
  caseRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  caseMain: { flex: 1, display: "flex", flexDirection: "column", gap: 2 } satisfies CSSProperties,
  caseName: { fontSize: 13.5, fontWeight: 600 } satisfies CSSProperties,
  caseMeta: { fontSize: 12, color: "var(--text-secondary)" } satisfies CSSProperties,
  caseActions: { display: "flex", gap: 6 } satisfies CSSProperties,
  progressRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  table: { width: "100%", borderCollapse: "collapse", fontSize: 13 } satisfies CSSProperties,
  th: {
    textAlign: "left",
    padding: "6px 8px",
    fontSize: 11,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  td: { padding: "6px 8px", borderBottom: "1px solid var(--border)" } satisfies CSSProperties,
  directionUp: { color: "var(--good, var(--accent))", display: "inline-flex", alignItems: "center", gap: 4 } satisfies CSSProperties,
  directionDown: { color: "var(--crit)", display: "inline-flex", alignItems: "center", gap: 4 } satisfies CSSProperties,
  directionFlat: { color: "var(--text-muted)", display: "inline-flex", alignItems: "center", gap: 4 } satisfies CSSProperties,
  incompleteBadge: {
    fontSize: 11,
    color: "var(--warn)",
    border: "1px solid var(--warn)",
    borderRadius: 4,
    padding: "1px 6px",
  } satisfies CSSProperties,
  comparePanel: {
    marginTop: 12,
    padding: 16,
    borderRadius: 8,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
    display: "flex",
    flexDirection: "column",
    gap: 14,
  } satisfies CSSProperties,
  compareMetrics: { display: "flex", gap: 16, flexWrap: "wrap" } satisfies CSSProperties,
  comparePrompts: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 } satisfies CSSProperties,
  promptBox: {
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12,
    whiteSpace: "pre-wrap",
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: 10,
    maxHeight: 240,
    overflow: "auto",
  } satisfies CSSProperties,
  promptLineChanged: { background: "var(--warn-bg)" } satisfies CSSProperties,
  warningBanner: {
    fontSize: 12.5,
    color: "var(--warn)",
    display: "flex",
    alignItems: "center",
    gap: 6,
  } satisfies CSSProperties,
  trendRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "6px 0",
  } satisfies CSSProperties,
  trendLabel: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12.5,
    minWidth: 90,
  } satisfies CSSProperties,
  trendSwatch: {
    display: "inline-block",
    width: 10,
    height: 10,
    borderRadius: 2,
  } satisfies CSSProperties,
  sparkline: {
    flex: 1,
    height: 28,
    maxWidth: 260,
  } satisfies CSSProperties,
  confirmBody: {
    padding: 20,
    fontSize: 13.5,
  } satisfies CSSProperties,
  confirmFooter: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 8,
  } satisfies CSSProperties,
  detailPanelRow: { padding: 0, borderBottom: "1px solid var(--border)" } satisfies CSSProperties,
  detailPanel: {
    padding: "10px 12px",
    background: "var(--bg-surface)",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  detailCaseRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 12.5,
    padding: "4px 0",
  } satisfies CSSProperties,
  detailCaseName: { flex: 1 } satisfies CSSProperties,
  detailCaseMeta: { color: "var(--text-secondary)", minWidth: 90 } satisfies CSSProperties,
  detailCaseError: { color: "var(--crit)", flex: 1 } satisfies CSSProperties,
} as const;
